# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [ ]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from pathlib import Path

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [ ]:
# Upload credit_card_transactions.csv to Colab
from google.colab import files

csv_file = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [ ]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv("applicants_data.csv")

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [ ]:
# Review the data types associated with the columns
# YOUR CODE HERE
applicant_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [ ]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df.head()

  APPLICATION_TYPE       AFFILIATION  ... ASK_AMT IS_SUCCESSFUL
0              T10       Independent  ...    5000             1
1               T3       Independent  ...  108590             1
2               T5  CompanySponsored  ...    5000             0
3               T3  CompanySponsored  ...    6692             1
4               T3       Independent  ...  142590             1

[5 rows x 10 columns]

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [1]:
# Create a list of categorical variables 
categorical_variables = categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
# YOUR CODE HERE
categorical_variables

NameError: ignored

In [ ]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [ ]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [ ]:
# Create a DataFrame with the encoded variables
encoded_df = encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)

# Review the DataFrame
# YOUR CODE HERE
encoded_df.head()

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [ ]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numeric_data_df = applicant_data_df.loc[:,['STATUS','ASK_AMT','IS_SUCCESSFUL']]

encode_data_df = pd.concat([encoded_df, numeric_data_df] ,axis=1)


# Review the Dataframe
# YOUR CODE HERE
encode_data_df

       APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...   ASK_AMT  IS_SUCCESSFUL
0                       1.0                   0.0  ...      5000              1
1                       0.0                   0.0  ...    108590              1
2                       0.0                   0.0  ...      5000              0
3                       0.0                   0.0  ...      6692              1
4                       0.0                   0.0  ...    142590              1
...                     ...                   ...  ...       ...            ...
34294                   0.0                   0.0  ...      5000              0
34295                   0.0                   0.0  ...      5000              0
34296                   0.0                   0.0  ...      5000              0
34297                   0.0                   0.0  ...      5000              1
34298                   0.0                   0.0  ...  36500179              0

[34299 rows x 117 columns]

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [ ]:
# Define the target set y using the IS_SUCCESSFUL column
y = encode_data_df['IS_SUCCESSFUL']

# Display a sample of y
# YOUR CODE HERE
y[:10]

0    1
1    1
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    0
Name: IS_SUCCESSFUL, dtype: int64

In [ ]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encode_data_df.drop(columns=['IS_SUCCESSFUL'])

# Review the features DataFrame
# YOUR CODE HERE
X[:5]

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  STATUS  ASK_AMT
0                   1.0                   0.0  ...       1     5000
1                   0.0                   0.0  ...       1   108590
2                   0.0                   0.0  ...       1     5000
3                   0.0                   0.0  ...       1     6692
4                   0.0                   0.0  ...       1   142590

[5 rows x 116 columns]

### Step 6: Split the features and target sets into training and testing datasets.

In [ ]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [ ]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled =  X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1) // 2 

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [ ]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [ ]:
# Create the Sequential model instance
nn = Sequential()

In [ ]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [ ]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [ ]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [ ]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 58)                6786
_________________________________________________________________
dense_1 (Dense)              (None, 29)                1711
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 30
=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [ ]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Fit the model using 50 epochs and the training data
# YOUR CODE HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5797 - accuracy: 0.7209
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7292
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7301
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7322
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7326
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7332
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7340
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7357
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7348
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7355
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7359
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7371
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7372
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7365
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7370
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7376
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7374
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7385
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7385
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7385
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7373
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7380
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7395
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7391
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7397
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7387
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7399
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7399
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7388
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7394
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7393
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7401
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7402
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7406
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7404
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7401
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7401
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7404
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7407
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7405
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7407
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7405
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7405
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7401
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7410
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7406
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7412
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7404
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7413

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [ ]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5534 - accuracy: 0.7303
Loss: 0.5534192323684692, Accuracy: 0.7302623987197876

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [ ]:
# Set the model's file path
file_path = Path("./Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
# YOUR CODE HERE
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features_1 = len(X_train.iloc[0])

# Review the number of features
number_input_features_1

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 2

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 8

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

8

In [ ]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [ ]:
# First hidden layer
hidden_nodes_layer1_A1 =  (number_input_features_1 + 1) // 2 


# Output layer
hidden_nodes_layer2_A2 = (hidden_nodes_layer1_A1 + 1) // 2


# Check the structure of the model
# YOUR CODE HERE
hidden_nodes_layer1_A1

58

In [ ]:
hidden_nodes_layer2_A2

29

In [ ]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 7.8675 - accuracy: 0.0023

#### Alternative Model 2

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features_2 = len(X_train.iloc[0])

# Review the number of features
number_input_features_2

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 18

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features_2 + number_output_neurons_A2) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

67

In [ ]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [ ]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="LeakyReLU"))

# Output layer
nn_A2.add(Dense(units=1, activation="sigmoid"))

# Check the structure of the model
# YOUR CODE HERE
nn_A2.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_5 (Dense)              (None, 58)                6786
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 59
=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
# YOUR CODE HERE
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Fit the model
# YOUR CODE HERE
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7341
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7344
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7341
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7356
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7352
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7325
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7340
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7356
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7348
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7330
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7340
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7333
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7341
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7343
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7341
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7343
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7340
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7349
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7348
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7343
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7353
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7353
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7343
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7359
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7348
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7360
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7349
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7355
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7344
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7357
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7356
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7355
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7334
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7359
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7355
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7365
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7346
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7360
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7340
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7355
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7357
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7347
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7358
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7355
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7353
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7350
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7360
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7347
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7364
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7365

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [ ]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test 
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5568 - accuracy: 0.7289
Loss: 0.5568105578422546, Accuracy: 0.728863000869751

In [ ]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 7.8073 - accuracy: 0.0031
Loss: 7.807292461395264, Accuracy: 0.0031486880034208298

In [ ]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5561 - accuracy: 0.7312
Loss: 0.5561349987983704, Accuracy: 0.731195330619812

### Step 3: Save each of your alternative models as an HDF5 file.

In [ ]:
# Set the file path for the first alternative model
file_path = './Resources/AlphabetSoup_A1.h5'

# Export your model to a HDF5 file
# YOUR CODE HERE
nn_A1.save(file_path)

In [ ]:
# Set the file path for the second alternative model
file_path = './Resources/AlphabetSoup_A2.h5'

# Export your model to a HDF5 file
nn_A2.save(file_path)